* Diseño de Interfaces - Creación de una guía de estilos para una aplicación
El objetivo de esta práctica es crear una pequeña guía de estilos siguiendo las recomendaciones expuestas en:
- https://pedroprieto.github.io/post/planificacion-fundamentos/
- https://pedroprieto.github.io/post/planificacion-guia-estilo/

** Temática
La guía de estilos se creará para una aplicación de temática a vuestra elección, por ejemplo una API para la gestión de usuarios de una agencia de viajes, una tienda online, ...

** Contenidos
La guía de estilos deberá incluir:
- *Nombre y apellidos* del autor al comienzo del documento.
- Breve *descripción de las características* indicando qué información va a albergar la aplicación a diseñar.
- *Tipografías* a utilizar, incluyendo una imagen de cada tipo de letra a utilizar. En [[https://fonts.google.com/][Google Fonts]] están disponibles.
- *Gama de colores*, incluyendo como mínimo un color principal, un color de fondo o contraste y una gama de colores complementarios del color principal.
- Un *logo* diseñado con el programa [[https://inkscape.org/es/][Inkscape]]. Puedes utilizar el [[https://youtu.be/zhnAHqQQ9gc][videotutorial incluido en el curso]] como referencia. El logo debe incluir un *texto con tu nombre y apellidos*.
- Referencia al tipo de *estructura de capas* que se utilizará. Para este punto puedes hacer un pequeño diagrama con el propio programa [[https://inkscape.org/es/][Inkscape]] o utilizar alguna herramienta online como https://www.draw.io/. Este tema se desarrollará más adelante en el apartado de prototipos, así que lo que se pide es un diseño muy sencillo basado exclusivamente en *bloques o cajas*.
- *Elementos gráficos* con referencia a iconos, formatos de imagen, etc.
- Cualquier otra información considerada de interés.

** Formato de la entrega
- Cada alumno dispondrá de un repositorio en GitHub para su trabajo personal. Dicho repositorio se creará haciendo un folk en el repositorio https://github.com/DI-23-24/Practica2
- Todos los archivos de la práctica se guardarán en el repositorio y se subirán a GitHub periódicamente. Es conveniente ir subiendo los cambios aunque no sean definitivos.
- La guía de estilos se realizará en cualquier programa de *edición de textos* (LibreOffice Writer, Microsoft Word,...) o equivalente, pero se *deberá guardar en el repositorio en formato PDF*.
- La guía debe ser breve (*no más de 3 páginas*) y estar correctamente maquetada.
- Se deberá incluir el *logo* en formato ~SVG~ y ~PNG~ dentro del repositorio.
- Una vez *finalizada* la tarea se debe crear un ~Issue~ en el repositorio haciendo referencia al profesor incluyendo el texto ~@yosies~ dentro del ~Issue~.
